name: Docker - Registry Orchestrator
on:
  push:
    branches:
      - main

jobs:
  docker-registry-orchestrator:
    name: Docker Registry Orchestrator
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current git repo
        uses: actions/checkout@v2
        token: ${{ secrets.GIT_AUTOMATION_USER_TOKEN }}
      - name: Install Trivy
        run: |
          bash install.sh
      - name: Log in to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Install Trivy
        run: |
          bash docker-registry-orchestrator.sh ${{ secrets.DOCKERHUB_USERNAME }}
