name: Docker Builder
on:
  push:
    branches:
      - main

jobs:
  builder:
    name: Docker Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current git repo
        uses: actions/checkout@v2
      - name: Install Trivy
        run: |
          bash install.sh
      - name: Log in to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Install Trivy
        run: |
          bash docker-builder.sh zachroofsec
