# +--------------------+
# SUMMARY
# +--------------------+

## Before modifying the code within a Github Repository, a peer review must occur
## This peer review occurs within a "Pull Request"
## When a Pull Request occurs, this workflow will use Trivy to scan for vulnerabilities

## Github Action Overview
## https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#overview

# +--------------------+
# MAIN LOGIC
# +--------------------+

name: Security - Docker - Scan

## Run workflow when ANY new changes are proposed
## Workflow runs within an isolated environment
on: [pull_request]

jobs:
  scan:
    name: Scan Docker Images
    runs-on: ubuntu-20.04
    steps:
      # Allow isolated environment access to ps-trivy Git repo
      - name: Checkout Current Git Repo
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          # Run install script at ps-trivy/install.sh
          bash install.sh

      - name: Execute Trivy Scans
        run: |
          bash docker-scan.sh
