name: Scan Docker Images
on: [pull_request]

jobs:
  scan:
    name: Scan Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current git repo
        uses: actions/checkout@v2
      - name: Install Trivy
        run: |
          bash install.sh
      - name: Install Trivy
        run: |
          bash docker-scan.sh
