## Descripción general de Github Actions
## https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#overview

# +--------------------+
# LÓGICA PRINCIPAL
# +--------------------+

name: Security - Docker - Scan

on: [pull_request] #


jobs:
  scan:
    name: Escanear Docker Imágenes
    runs-on: ubuntu-20.04 #


    steps:
      - name: Permitir acceso repositorio #


        uses: actions/checkout@v2

      - name: Instalar Trivy
        run: |
          bash install.sh

      - name: Ejecutar escáner de Trivy
        run: |
          bash docker-scan.sh 
